name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - Poly-Pixel
body: 
  - type: markdown
    attributes:
      value: Fill out the fields below, and it will be reviewed as soon as possible. Remember to follow the Code of Conduct
  - type: input
    id: page
    attributes:
      label: Page
      description: What page did the bug occur on?
      placeholder: ex. /dashboard
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened? Please be as clear as possible
      placeholder: ex. I got an error message...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: How can we reproduce this bug?
      placeholder: ex. Step 1, Step 2... 
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additonal context
      description: Add any additonal context about the issue here
    validations:
      required: false
